name: CI/CD - FCG.Functions

on:
  push:
    branches:
      - '**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Unit Tests with Coverage
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

  deploy-dev:
    needs: build-test
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      - name: Deploy to Azure Functions - DEV
        run: |
          func azure functionapp publish func-fcg-payments-dev \
            --csharp \
            --set-env-vars \
                "ServiceBusConnection=${{ secrets.SERVICEBUS_CONNECTION }}" \
                "PaymentsAPI_Url=${{ vars.PAYMENTS_API_URL }}" \
                "PaymentsAPI_Token=${{ secrets.PAYMENTS_API_TOKEN }}" \
                "AspNetCore__Environment=${{ vars.ENV }}"

  deploy-uat:
    needs:
      - build-test
      - deploy-dev
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      - name: Deploy to Azure Functions - UAT
        run: |
          func azure functionapp publish func-fcg-payments-uat \
            --csharp \
            --set-env-vars \
                "ServiceBusConnection=${{ secrets.SERVICEBUS_CONNECTION }}" \
                "PaymentsAPI_Url=${{ vars.PAYMENTS_API_URL }}" \
                "PaymentsAPI_Token=${{ secrets.PAYMENTS_API_TOKEN }}" \
                "AspNetCore__Environment=${{ vars.ENV }}"

  deploy-prd:
    needs: 
      - build-test
      - deploy-dev
      - deploy-uat
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: PRD

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4
          
      - name: Deploy to Azure Functions - PRD
        run: |
          func azure functionapp publish azure-functions-project-prd \
            --csharp \
            --set-env-vars \
                "ServiceBusConnection=${{ secrets.SERVICEBUS_CONNECTION }}" \
                "PaymentsAPI_Url=${{ vars.PAYMENTS_API_URL }}" \
                "PaymentsAPI_Token=${{ secrets.PAYMENTS_API_TOKEN }}" \
                "AspNetCore__Environment=${{ vars.ENV }}"